changesetIgnorePatterns:
  - "**/__tests__/**"
  - "**/*.md"

nodeLinker: pnp
pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.5.3.cjs

logFilters:
  - code: YN0060             # Suppress peer dependency mismatch warnings
    level: discard