name: Benchmark

on:
  pull_request:
    branches:
      - master
    paths:
      - 'packages/normalizr/**'
      - 'packages/core/**'
  push:
    branches:
      - master
    paths:
      - 'packages/normalizr/**'
      - 'packages/core/**'
jobs:
  benchmark:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2-beta
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Run benchmark
      run: |
        npm install -g corepack
        corepack enable
        yarn install --immutable
        NODE_ENV=production BROWSERSLIST_ENV=modern yarn lerna run --scope @rest-hooks/core --include-dependencies build && yarn workspace example-benchmark start | tee output.txt


    # PR comments on changes
    - name: Download previous benchmark data (PR)
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/cache@v3
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark-pr-${{ env.GITHUB_RUN_NUMBER }}
        restore-keys: |
          ${{ runner.os }}-benchmark
    - name: Store benchmark result (PR)
      if: ${{ github.event_name == 'pull_request' }}
      uses: rhysd/github-action-benchmark@v1
      with:
        tool: 'benchmarkjs'
        output-file-path: output.txt
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        gh-pages-branch: 'gh-pages-bench'
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '150%'
        comment-always: true
        fail-on-alert: false
        alert-comment-cc-users: '@ntucker'
        # we only want to compare against master, so do not save for PR
        save-data-file: false
        auto-push: false

    # master reports to history
    - name: Download previous benchmark data (main)
      if: ${{ github.event_name == 'push' }}
      uses: actions/cache@v3
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark
    - name: Store benchmark result (main)
      if: ${{ github.event_name == 'push' }}
      uses: rhysd/github-action-benchmark@v1
      with:
        tool: 'benchmarkjs'
        output-file-path: output.txt
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        gh-pages-branch: 'gh-pages-bench'
        auto-push: true
        fail-on-alert: false
