name: Compressed Size

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
    paths:
      - 'packages/**'
      - 'yarn.lock'

jobs:
  compressed-size-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: compressed-size-action
      uses: preactjs/compressed-size-action@v2
      continue-on-error: true
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        build-script: "build:bundle"
